#!/bin/sh

# original config script by rw-r-r-0644
# modified by GaryOderNichts
# modified by hito16

if [ -z "$DEVKITPRO" -o -z "$DEVKITPPC" ]; then
  echo required variable must be set, exiting...
  echo DEVKITPRO="$DEVKITPRO"
  echo DEVKITPPC="$DEVKITPPC"
  exit 1
fi
export WUT_ROOT=$DEVKITPRO/wut
  
export PATH=$DEVKITPPC/bin:$PATH
export ARCH="-mcpu=750 -meabi -mhard-float"
export CFLAGS="-fomit-frame-pointer -ffast-math -fno-math-errno -funsafe-math-optimizations -ffinite-math-only -fno-trapping-math -O3 -Ofast"

./configure --prefix=$DEVKITPRO/portlibs/ppc/ \
--enable-cross-compile \
--cross-prefix=$DEVKITPPC/bin/powerpc-eabi- \
--disable-shared \
--disable-runtime-cpudetect \
--disable-programs \
--disable-doc \
--disable-everything \
--enable-decoder=mpeg4,h264_wiiu,aac,ac3,mp3 \
--enable-demuxer=mov,h264 \
--enable-bsf=h264_mp4toannexb \
--enable-filter=rotate,transpose \
--enable-protocol=file \
--disable-network \
--enable-static \
--arch=ppc \
--cpu=750 \
--target-os=none \
--extra-cflags=" -D__WIIU__ $CFLAGS $ARCH -I$WUT_ROOT/include" \
--extra-cxxflags=" -D__WIIU__ $CFLAGS -fno-rtti -fno-exceptions -std=gnu++11 $ARCH" \
--extra-ldflags=" -Wl,-q -Wl,-z,nocopyreloc -specs=$WUT_ROOT/share/wut.specs -L$WUT_ROOT/lib -lwut" \
--disable-debug \
--disable-bzlib \
--disable-iconv \
--disable-lzma \
--disable-securetransport \
--disable-xlib \
--disable-zlib  

# A default build only has the following codecs (decoder only)
# Video h263
# Video mpeg4
# Video aac
# Audio ac3
# Audio mp3
#
# to enable x264, build and install 
# --enable-libx264 \
# --enable-gpl \
# --disable-x86asm \