#!/bin/sh

# original config script by rw-r-r-0644
# modified by GaryOderNichts
# modified by hito16

# you probably don't want this
# This configure script will build the ffplay media player with SDL2
# 
# The configure script is too rigid, and the way devkitpro + portlibs 
# lays out packages is too unfamilar to the script.   A change in either
# would make building easier.
#
# To get around this, we apply two non-permanent, non-invasive pathes
# to the configure script and a generated mk include.

if [ -z "$DEVKITPRO" -o -z "$DEVKITPPC" ]; then
  echo required variable must be set, exiting...
  echo DEVKITPRO="$DEVKITPRO"
  echo DEVKITPPC="$DEVKITPPC"
  exit 1
fi
export WUT_ROOT=$DEVKITPRO/wut
  
export PATH=$DEVKITPPC/bin:$PATH
export ARCH="-mcpu=750 -meabi -mhard-float"
export CFLAGS="-fomit-frame-pointer -ffast-math -fno-math-errno -funsafe-math-optimizations -ffinite-math-only -fno-trapping-math -O3 -Ofast -std=c11"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/devkitpro/portlibs/wiiu/lib/pkgconfig:/opt/devkitpro/portlibs/ppc/lib/pkgconfig"
export SDL_CFLAGS=$($DEVKITPRO/portlibs/wiiu/bin/powerpc-eabi-pkg-config --cflags sdl2)
export SDL_LDFLAGS=$($DEVKITPRO/portlibs/wiiu/bin/powerpc-eabi-pkg-config --libs sdl2)
export COMPAT_CFLAGS=-I./compat/stdbit/


do_configure() {
./configure.patched  --prefix=$DEVKITPRO/portlibs/wiiu/ \
--enable-cross-compile \
--cross-prefix=$DEVKITPPC/bin/powerpc-eabi- \
--pkgconfigdir=$DEVKITPRO/portlibs/wiiu/lib/pkgconfig \
--enable-sdl2 \
--enable-swresample \
--disable-shared \
--disable-runtime-cpudetect \
--disable-doc \
--disable-protocols \
--enable-protocol=file \
--disable-network \
--enable-static \
--arch=ppc \
--cpu=750 \
--target-os=none \
--extra-cflags=" -D__WIIU__ $CFLAGS $ARCH $COMPAT_CFLAGS -I$WUT_ROOT/include $SDL_CFLAGS" \
--extra-cxxflags=" -D__WIIU__ $CFLAGS -fno-rtti -fno-exceptions -std=gnu++11 $ARCH" \
--extra-ldflags=" -Wl,-q -Wl,-z,nocopyreloc -specs=$WUT_ROOT/share/wut.specs $SDL_LDFLAGS -L$WUT_ROOT/lib  -lwut" \
--disable-debug \
--disable-bzlib \
--disable-iconv \
--disable-lzma \
--disable-securetransport \
--disable-xlib \
--disable-zlib  
}

do_configure
